version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ktr0731/evans
    docker:
      - image: ktr0731/circleci-evans

    steps:
      - checkout

      - run:
          name: build
          command: make build

      - run:
          name: test
          command: make test

      - run:
          name: update GitHub releases and update brew formula
          command: make brew-update
