version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ktr0731/evans
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout

      - run:
          name: build
          command: make build

      - run:
          name: test
          command: make test
